import { statSync } from "node:fs";
import { join, relative } from "node:path";
import { compareStrings } from "./canonical-json.js";
import { loadConfig, type LoadedConfig } from "./config.js";
import {
  claimRecordSchema,
  isSafeRelativePath,
  oratlasManifestSchema,
  unicodeCodePointLength,
  type ClaimRecord,
  type OratlasManifest,
} from "./contracts/index.js";
import { OratlasMystError } from "./errors.js";
import { claimDeclarationSha256, sha256 } from "./hash.js";
import {
  CLAIMS_ARTIFACT_PATH,
  MANIFEST_FILE_NAME,
  exportProject,
  publicationSourcesSha256,
} from "./export.js";
import { indexLines, parseDocument } from "./parse-claims.js";
import { discoverPages, readProjectFile, resolveInsideProject } from "./project.js";
import { MAX_ARTIFACT_BYTES, readReviewManifest } from "./review-manifest.js";

export interface ValidationIssue {
  code: string;
  message: string;
  /** Where the problem was found, relative to the project root. */
  where?: string;
}

export interface ValidationResult {
  ok: boolean;
  errors: ValidationIssue[];
  warnings: ValidationIssue[];
  /** Number of claim records read from the artifact. */
  records: number;
  manifest?: OratlasManifest;
}

export interface ValidateOptions {
  projectRoot?: string;
  /**
   * Also re-run the export in memory and require it to reproduce the artifacts
   * on disk byte for byte. On by default; this is what makes the artifacts
   * verifiably a function of the source.
   */
  checkConsistency?: boolean;
}

function issue(code: string, message: string, where?: string): ValidationIssue {
  return { code, message, ...(where ? { where } : {}) };
}

function readOutputFile(
  outputDir: string,
  projectRoot: string,
  relativePath: string,
  maxBytes: number,
): { content: string } | { error: ValidationIssue } {
  const target = join(outputDir, relativePath);
  const where = relative(projectRoot, target) || relativePath;
  try {
    const stats = statSync(target);
    if (!stats.isFile()) {
      return { error: issue("artifact-not-a-file", `Not a regular file.`, where) };
    }
    if (stats.size > maxBytes) {
      return {
        error: issue("artifact-too-large", `Larger than the ${maxBytes} byte cap.`, where),
      };
    }
  } catch {
    return {
      error: issue(
        "artifact-missing",
        `Artifact is missing. Run \`oratlas-myst export\` first.`,
        where,
      ),
    };
  }
  const outputRelative = relative(projectRoot, outputDir);
  return {
    content: readProjectFile(projectRoot, join(outputRelative, relativePath), maxBytes),
  };
}

/**
 * Parse a claims JSONL artifact strictly.
 *
 * Unlike ORAtlas's tolerant importer, this validator fails on the first
 * malformed line: these artifacts are generated by this tool, so a bad line
 * means the file was hand-edited or corrupted, not that a third party wrote a
 * slightly different dialect.
 */
function parseClaimsJsonl(content: string, where: string): ClaimRecord[] | ValidationIssue[] {
  const errors: ValidationIssue[] = [];
  const records: ClaimRecord[] = [];
  const lines = content.split("\n");
  lines.forEach((line, index) => {
    if (line.trim().length === 0) {
      if (index !== lines.length - 1) {
        errors.push(issue("jsonl-blank-line", `Line ${index + 1} is blank.`, where));
      }
      return;
    }
    let value: unknown;
    try {
      value = JSON.parse(line);
    } catch (error) {
      errors.push(
        issue(
          "jsonl-unparsable",
          `Line ${index + 1} is not valid JSON: ${error instanceof Error ? error.message : String(error)}`,
          where,
        ),
      );
      return;
    }
    const parsed = claimRecordSchema.safeParse(value);
    if (!parsed.success) {
      for (const problem of parsed.error.issues) {
        errors.push(
          issue(
            "claim-record-invalid",
            `Line ${index + 1}: ${problem.path.join(".") || "(root)"}: ${problem.message}`,
            where,
          ),
        );
      }
      return;
    }
    records.push(parsed.data);
  });
  return errors.length > 0 ? errors : records;
}

function sliceCodePoints(source: string, start: number, end: number): string {
  return Array.from(source).slice(start, end).join("");
}

/**
 * Validate one publication's generated ORAtlas artifacts.
 *
 * Validation is entirely local: no network access is performed or required.
 * Everything it can check against the publication source, it does check.
 */
export function validateProject(options: ValidateOptions = {}): ValidationResult {
  const projectRoot = options.projectRoot ?? process.cwd();
  const errors: ValidationIssue[] = [];
  const warnings: ValidationIssue[] = [];

  let config: LoadedConfig;
  try {
    config = loadConfig(projectRoot);
  } catch (error) {
    if (error instanceof OratlasMystError) {
      return {
        ok: false,
        errors: [issue(error.code, [error.message, error.detail].filter(Boolean).join(" "))],
        warnings,
        records: 0,
      };
    }
    throw error;
  }

  const outputDir = resolveInsideProject(projectRoot, config.oratlas.output);

  // --- manifest ------------------------------------------------------------
  const manifestFile = readOutputFile(outputDir, projectRoot, MANIFEST_FILE_NAME, 4_000_000);
  if ("error" in manifestFile) {
    return { ok: false, errors: [manifestFile.error], warnings, records: 0 };
  }
  const manifestWhere = join(config.oratlas.output, MANIFEST_FILE_NAME);
  let manifestValue: unknown;
  try {
    manifestValue = JSON.parse(manifestFile.content);
  } catch (error) {
    return {
      ok: false,
      errors: [
        issue(
          "manifest-unparsable",
          `Not valid JSON: ${error instanceof Error ? error.message : String(error)}`,
          manifestWhere,
        ),
      ],
      warnings,
      records: 0,
    };
  }
  const parsedManifest = oratlasManifestSchema.safeParse(manifestValue);
  if (!parsedManifest.success) {
    return {
      ok: false,
      errors: parsedManifest.error.issues.map((problem) =>
        issue(
          "manifest-invalid",
          `${problem.path.join(".") || "(root)"}: ${problem.message}`,
          manifestWhere,
        ),
      ),
      warnings,
      records: 0,
    };
  }
  const manifest = parsedManifest.data;

  // --- declared paths ------------------------------------------------------
  for (const [label, path] of [
    ["adapter.xref", manifest.adapter.xref],
    ["artifacts.claims.path", manifest.artifacts.claims.path],
    ...(manifest.oratlas
      ? ([["oratlas.reviewManifest", manifest.oratlas.reviewManifest]] as const)
      : []),
  ] as const) {
    if (!isSafeRelativePath(path)) {
      errors.push(
        issue("unsafe-path", `${label} is not a safe relative path: ${path}`, manifestWhere),
      );
    }
  }

  // --- claims artifact -----------------------------------------------------
  const claimsPath = manifest.artifacts.claims.path;
  const claimsFile = isSafeRelativePath(claimsPath)
    ? readOutputFile(outputDir, projectRoot, claimsPath, MAX_ARTIFACT_BYTES)
    : { error: issue("unsafe-path", `Refusing to read unsafe path: ${claimsPath}`, manifestWhere) };
  if ("error" in claimsFile) {
    return { ok: false, errors: [...errors, claimsFile.error], warnings, records: 0 };
  }
  const claimsWhere = join(config.oratlas.output, claimsPath);

  if (sha256(claimsFile.content) !== manifest.artifacts.claims.sha256) {
    errors.push(
      issue(
        "artifact-digest-mismatch",
        `Claims artifact digest does not match artifacts.claims.sha256 in the manifest.`,
        claimsWhere,
      ),
    );
  }

  const parsedClaims = parseClaimsJsonl(claimsFile.content, claimsWhere);
  if (!Array.isArray(parsedClaims) || (parsedClaims.length > 0 && "code" in parsedClaims[0]!)) {
    return {
      ok: false,
      errors: [...errors, ...(parsedClaims as ValidationIssue[])],
      warnings,
      records: 0,
      manifest,
    };
  }
  const records = parsedClaims as ClaimRecord[];

  if (records.length !== manifest.artifacts.claims.records) {
    errors.push(
      issue(
        "artifact-record-count-mismatch",
        `Manifest declares ${manifest.artifacts.claims.records} record(s) but the artifact contains ${records.length}.`,
        claimsWhere,
      ),
    );
  }

  // --- unique ids ----------------------------------------------------------
  const seen = new Map<string, number>();
  records.forEach((record, index) => {
    const previous = seen.get(record.id);
    if (previous !== undefined) {
      errors.push(
        issue(
          "duplicate-claim-id",
          `Claim id "${record.id}" appears on records ${previous + 1} and ${index + 1}.`,
          claimsWhere,
        ),
      );
      return;
    }
    seen.set(record.id, index);
  });

  // --- declaration authority ----------------------------------------------
  const delegated = manifest.artifacts.claims.declarations === "review-manifest";
  for (const record of records) {
    const hasDeclarationFields =
      record.text !== undefined ||
      record.claimType !== undefined ||
      record.qualification !== undefined;
    if (delegated && hasDeclarationFields) {
      errors.push(
        issue(
          "declaration-authority-violation",
          `Claim "${record.id}" carries claim declaration fields, but the manifest delegates claim declarations to the review manifest.`,
          claimsWhere,
        ),
      );
    }
    if (!delegated && record.text === undefined) {
      errors.push(
        issue(
          "declaration-missing-text",
          `Claim "${record.id}" has no text, but the manifest does not delegate claim declarations.`,
          claimsWhere,
        ),
      );
    }
  }

  if (manifest.oratlas && isSafeRelativePath(manifest.oratlas.reviewManifest)) {
    try {
      const recognized = readReviewManifest(projectRoot, manifest.oratlas.reviewManifest);
      if (recognized.claimsArtifactPath) {
        const missing = records
          .map((record) => record.id)
          .filter((id) => !recognized.declaredClaimIds.has(id))
          .sort(compareStrings);
        if (missing.length > 0) {
          errors.push(
            issue(
              "review-manifest-claim-unknown",
              `Claim(s) not declared by ${recognized.claimsArtifactPath}: ${missing.join(", ")}.`,
              manifest.oratlas.reviewManifest,
            ),
          );
        }
      } else if (delegated) {
        errors.push(
          issue(
            "review-manifest-no-claims",
            `Manifest delegates claim declarations, but the review manifest declares no claims artifact.`,
            manifest.oratlas.reviewManifest,
          ),
        );
      }
    } catch (error) {
      errors.push(
        issue(
          error instanceof OratlasMystError ? error.code : "review-manifest-unreadable",
          error instanceof Error ? error.message : String(error),
          manifest.oratlas.reviewManifest,
        ),
      );
    }
  }

  // --- publication version digest -----------------------------------------
  // The version digest is what gives a publication an exact version identity
  // even when it exposes no repository, DOI or archive, so it is checked
  // against the current document set rather than taken on trust.
  try {
    const pages = discoverPages(config).pages;
    const documents = pages.map((page) => ({
      path: page.path,
      sha256: sha256(readProjectFile(projectRoot, page.path)),
    }));
    const expected = publicationSourcesSha256(documents);
    if (expected !== manifest.publication.version.sourcesSha256) {
      errors.push(
        issue(
          "publication-version-mismatch",
          `publication.version.sourcesSha256 does not match the current document set (${documents.length} page(s)). A page changed, was added, or was removed since the last export.`,
          manifestWhere,
        ),
      );
    }
  } catch (error) {
    errors.push(
      issue(
        error instanceof OratlasMystError ? error.code : "page-discovery-failed",
        `Could not enumerate the publication's pages: ${error instanceof Error ? error.message : String(error)}`,
      ),
    );
  }

  // --- source binding, hashes, selectors, targets --------------------------
  const documentCache = new Map<string, { source: string; sha: string } | null>();
  const parseCache = new Map<string, ReturnType<typeof parseDocument> | null>();

  for (const record of records) {
    const path = record.source.documentPath;
    if (!documentCache.has(path)) {
      try {
        const source = readProjectFile(projectRoot, path);
        documentCache.set(path, { source, sha: sha256(source) });
      } catch (error) {
        documentCache.set(path, null);
        errors.push(
          issue(
            error instanceof OratlasMystError ? error.code : "source-unreadable",
            error instanceof Error ? error.message : String(error),
            path,
          ),
        );
      }
    }
    const document = documentCache.get(path);
    if (!document) continue;

    if (document.sha !== record.source.documentSha256) {
      errors.push(
        issue(
          "source-digest-mismatch",
          `Claim "${record.id}" records a source digest that does not match ${path}. The source changed since the last export.`,
          path,
        ),
      );
      continue;
    }

    const { lines } = indexLines(document.source);
    if (record.source.endLine > lines.length) {
      errors.push(
        issue(
          "source-span-out-of-range",
          `Claim "${record.id}" spans to line ${record.source.endLine}, past the end of ${path}.`,
          path,
        ),
      );
      continue;
    }
    const blockSource = lines.slice(record.source.startLine - 1, record.source.endLine).join("\n");
    if (sha256(blockSource) !== record.source.blockSha256) {
      errors.push(
        issue(
          "block-digest-mismatch",
          `Claim "${record.id}" records a block digest that does not match lines ${record.source.startLine}-${record.source.endLine} of ${path}.`,
          path,
        ),
      );
    }

    const { start, end } = record.selector.textPosition;
    const quoted = sliceCodePoints(document.source, start, end);
    if (quoted !== record.selector.textQuote.exact) {
      errors.push(
        issue(
          "selector-mismatch",
          `Claim "${record.id}": the recorded quote does not appear at code points ${start}-${end} of ${path}.`,
          path,
        ),
      );
    }
    if (end - start !== unicodeCodePointLength(record.selector.textQuote.exact)) {
      errors.push(
        issue(
          "selector-length-mismatch",
          `Claim "${record.id}": text position length does not match the exact quote length.`,
          path,
        ),
      );
    }
    const expectedPrefix = sliceCodePoints(document.source, Math.max(0, start - 96), start);
    if ((record.selector.textQuote.prefix ?? "") !== expectedPrefix) {
      warnings.push(
        issue(
          "selector-prefix-mismatch",
          `Claim "${record.id}": recorded selector prefix does not match the source context.`,
          path,
        ),
      );
    }

    if (!parseCache.has(path)) {
      try {
        parseCache.set(path, parseDocument(document.source, path));
      } catch {
        parseCache.set(path, null);
      }
    }
    const parsed = parseCache.get(path);
    if (!parsed) {
      errors.push(issue("source-unparsable", `Could not parse ${path} as MyST Markdown.`, path));
      continue;
    }
    const occurrence = parsed.claims.find((claim) => claim.options.id === record.id);
    if (!occurrence) {
      errors.push(
        issue(
          "target-unresolved",
          `Claim "${record.id}" is recorded against ${path}, but no \`oratlas:claim\` with that id is declared there. Its cross-reference target does not exist.`,
          path,
        ),
      );
      continue;
    }
    const expectedDeclaration = claimDeclarationSha256({
      id: occurrence.options.id,
      body: occurrence.bodySource,
      claimType: occurrence.options.claimType,
      qualification: occurrence.options.qualification,
    });
    if (expectedDeclaration !== record.declarationSha256) {
      errors.push(
        issue(
          "declaration-digest-mismatch",
          `Claim "${record.id}": recorded declaration digest does not match the declaration in ${path}.`,
          path,
        ),
      );
    }
    if (!delegated && record.text !== undefined && record.text !== occurrence.text) {
      errors.push(
        issue(
          "text-mismatch",
          `Claim "${record.id}": recorded text does not match the claim body in ${path}.`,
          path,
        ),
      );
    }
  }

  // --- deterministic consistency with a fresh export -----------------------
  if (options.checkConsistency !== false && errors.length === 0) {
    try {
      // `--source-commit` is a build-time input, not something the project
      // carries, so a fresh export cannot rediscover it. Feed the recorded
      // commit back in, or every git-backed publication would report its own
      // artifacts as stale. The commit itself is not locally verifiable —
      // checking it needs the repository — so this comparison deliberately
      // covers everything *except* that value.
      const recordedCommit =
        manifest.publication.source?.type === "git"
          ? manifest.publication.source.commit
          : undefined;
      const fresh = exportProject({
        projectRoot,
        write: false,
        ...(recordedCommit ? { sourceCommit: recordedCommit } : {}),
      });
      for (const file of fresh.files) {
        const onDisk = file.path === MANIFEST_FILE_NAME ? manifestFile.content : claimsFile.content;
        const expectedPath = file.path === MANIFEST_FILE_NAME ? MANIFEST_FILE_NAME : claimsPath;
        if (expectedPath !== file.path) {
          warnings.push(
            issue(
              "artifact-path-nonstandard",
              `Manifest declares the claims artifact at "${claimsPath}"; a fresh export writes "${CLAIMS_ARTIFACT_PATH}".`,
              manifestWhere,
            ),
          );
          continue;
        }
        if (onDisk !== file.content) {
          errors.push(
            issue(
              "artifact-stale",
              `On-disk artifact differs from a fresh export of the current source. Re-run \`oratlas-myst export\`.`,
              join(config.oratlas.output, file.path),
            ),
          );
        }
      }
    } catch (error) {
      errors.push(
        issue(
          error instanceof OratlasMystError ? error.code : "export-failed",
          `Re-running the export to check consistency failed: ${error instanceof Error ? error.message : String(error)}`,
        ),
      );
    }
  }

  // --- static publication wiring -------------------------------------------
  const staticFiles = new Set(config.myst.staticFiles);
  const expectedManifestEntry = `${config.oratlas.output}/${MANIFEST_FILE_NAME}`;
  const expectedClaimsEntry = `${config.oratlas.output}/${claimsPath.split("/")[0]}`;
  for (const entry of [expectedManifestEntry, expectedClaimsEntry]) {
    if (!staticFiles.has(entry)) {
      warnings.push(
        issue(
          "static-files-not-declared",
          `myst.yml does not list "${entry}" under project.static_files, so the built site will not serve it at its root.`,
          "myst.yml",
        ),
      );
    }
  }

  return {
    ok: errors.length === 0,
    errors,
    warnings,
    records: records.length,
    manifest,
  };
}
